### ISSUE TITLE
Provide "remove additional files at destination"

### ISSUE THREAD

**Issue by Scooletz** [Azure/functions-action#33] opened 2020-05-08 07:56 UTC
After going through documentations I found no information about it, so I'm raising this issue.

`Remove additional files at destination` as in https://github.com/Azure/Azure-Functions/issues/564 is not available as a publish option.

**Comment by AmrutaKawade** [comment] 2020-08-20 13:47
Remove additional files at destination option is available in msdeploy. For function action we use kudu zip deploy method for deployment. as per kudu [documentation](https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url)

> Deletion of files no longer in the build: When a new build is deployed with zipdeploy, files and directories that were created by the previous deployment but are no longer present in the build will be deleted. Any other files and directories found in the site that aren't being overwritten by the deployment, such as those placed there via FTP or created by your app during runtime, will be preserved.


but i guess this is not happening as we have received similar issue.
Duplicate of #https://github.com/Azure/webapps-deploy/issues/20

there is open issue on kudu api repo as well https://github.com/projectkudu/kudu/issues/3183

**Comment by AmrutaKawade** [comment] 2020-08-24 10:37
currently we are unable to repro this? can you provide repro steps

**Comment by Scooletz** [comment] 2020-09-08 17:12
Thank you for the response @AmrutaKawade I'm aware of the kudu zip deploy, but I fail to find it in the documentation for this actions provided on the action page https://github.com/marketplace/actions/azure-functions-action

**Comment by 20shivangi** [comment] 2020-09-09 05:57
@N-Usha Please check this issue. Some things are missing in documentation.

**Comment by N-Usha** [comment] 2020-09-18 05:49
I added this detail to the documentation. Closing this issue. Thanks!

**Closed by N-Usha** 2020-09-18 05:49 UTC
Labels: documentation

**Comment by Scooletz** [comment] 2020-09-18 08:38
Hey @N-Usha Could you provide a link to a PR for this change? It'd be great if one could follow the link and find the difference.

**Comment by Scooletz** [comment] 2020-09-18 08:42
@AmrutaKawade According to the updated doc 

> "Remove additional files at destination" is not supported by Kudu deploy method which is used in this action and should be handled separately.

so I think that your comment https://github.com/Azure/functions-action/issues/33#issuecomment-677675018 might not be applicable. As far as I see it, it makes this issue valid again, because it intent was not to have a documentation updated, but rather address the lack of functionality.

**Comment by maximivanov** [comment] 2020-12-06 19:49
I've just confirmed the following (undesired) scenario:

1. New file added to git and branch pushed to Github
2. Deployment triggered with `functions-action` in it. Destination: Linux Premium Function App
3. I can see the new file on the Function App / App Files page in Azure Portal
4. I remove the file and commit/push
5. Deployment triggered
6. File is still visible in the App Files.

I was exploring Github Actions as a replacement for an Azure DevOps pipeline (that would make our setup much simpler) but with this missing feature I don't think it's ready yet. Hopefully it's on the roadmap.

**Comment by JasonKleban** [comment] 2021-08-18 12:30
So @N-Usha, how do we delete old functions?  

The Azure portal shows 

![image](https://user-images.githubusercontent.com/17498172/129897896-7f67e326-2aff-4874-a5d0-a65e1c53d359.png)

And there's no obvious way to get a yaml deployment with `azure/azure-functions` to clear them out?  And by not clearing them out, I see a bunch of ERROR noise in my logs at app startup regarding bad bindings for functions that I've already deleted in my source.
