### ISSUE TITLE
Releases 1.1.7 and 1.1.8 are not backwards compatible with 1.1.6

### ISSUE THREAD

**Issue by rue-kcarlton** [Azure/functions-action#50] opened 2020-11-18 21:23 UTC
Based on the changes introduced in v1.1.7, my release to Azure job is getting the following error:
```
##[Initialize]
##[ValidateParameter]
Error: Execution Exception (state: ValidateParameter) (step: Invocation)
Error:   Cannot read property 'indexOf' of undefined
Error:     TypeError: Cannot read property 'indexOf' of undefined
    at ParameterValidator.validateScmCredentialsSlotName (D:\a\_actions\Azure\functions-action\v1.1.7\lib\handlers\parameterValidator.js:158:42)
    at ParameterValidator.<anonymous> (D:\a\_actions\Azure\functions-action\v1.1.7\lib\handlers\parameterValidator.js:56:18)
    at Generator.next (<anonymous>)
    at fulfilled (D:\a\_actions\Azure\functions-action\v1.1.7\lib\handlers\parameterValidator.js:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Deployment Failed!
```
My job is running on `windows-latest` and is currently working now that I've specifically pinned `v1.1.6` as the version of this action to run.
My job is using a publish profile as the Deployment Credential, the publish profile was generated in July and has the following format (the names and passwords have been changed):
```
<publishData>
  <publishProfile profileName="my-api - Web Deploy" publishMethod="MSDeploy" publishUrl="my-api.scm.azurewebsites.net:443" msdeploySite="my-api" userName="$my-api" userPWD="***" destinationAppUrl="http://my-api.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites">
    <databases/>
  </publishProfile>
  <publishProfile profileName="my-api - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-blu-095.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="my-api\$my-api" userPWD="***" destinationAppUrl="http://my-api.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites">
    <databases/>
  </publishProfile>
  <publishProfile profileName="my-api - ReadOnly - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-blu-095dr.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="my-api\$my-api" userPWD="***" destinationAppUrl="http://my-api.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites">
    <databases/>
  </publishProfile>
</publishData>
```

**Comment by aksm-ms** [comment] 2020-11-19 04:31
@Hazhzeng Can you please take a look at this?

**Comment by aksm-ms** [comment] 2020-11-26 06:33
@Hazhzeng Can you please look into this?

**Comment by Hazhzeng** [comment] 2020-11-30 17:15
Hi @rue-kcarlton, thanks for raising the issue.
Based on the error logs, seems like the Github Action fails on slot validation.
Could you share me your workflow.yml? Just want to see if the **slot-name** variable is set.

**Comment by rue-kcarlton** [comment] 2020-11-30 17:21
@Hazhzeng here's my workflow snippet as it existed during the first of the failed runs:
```
   - name: Run Azure functions action to deploy ${{ steps.vars.outputs.RELEASE_NAME }} to ${{ env.FLEET }}
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        slot-name: staging
```
I think I may have figured out the issue... based on older documentation, I still have the `SCM_CREDENTIALS` secret set which includes the Azure Publish Profile, but not the `AZURE_FUNCTIONAPP_PUBLISH_PROFILE` secret.  I haven't been able to test my theory as I didn't want to release again over the holiday weekend (or on cyber Monday).

**Comment by Hazhzeng** [comment] 2020-11-30 18:57
Thanks @rue-kcarlton for the quick turn around. Yes, it is also worth try to change the line
```
publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
```
back to
```
publish-profile: ${{ secrets.SCM_CREDENTIALS }}
```

**Comment by aksm-ms** [comment] 2020-12-01 11:00
@rue-kcarlton Please let us know if the issue is still happening.

**Comment by rue-kcarlton** [comment] 2020-12-01 15:43
I attempted a release this morning with the change @Hazhzeng suggested (changing my `publish-profile` to the `secrets.SCM_CREDENTIALS`), but now I'm getting a new error:
```
##[Initialize]
##[ValidateParameter]
Successfully parsed SCM credential from old publishProfile
Error: Execution Exception (state: ValidateParameter) (step: Invocation)
Error:   At ValidateParameter, slot-name : SCM credential does not match slot-name.
Error: Deployment Failed!
```

**Comment by Hazhzeng** [comment] 2020-12-01 23:06
I see @rue-kcarlton, this action did a validation to ensure your publishProfile matches your slot. The line
```
publishUrl="my-api.scm.azurewebsites.net:443"
```
Should be something like 
```
publishUrl="my-api-slotname.scm.azurewebsites.net:443"
```
instead.

This issue happens when you download your publish profile in your main app instead of from your slot. Please try setting the **SCM_CREDENTIALS** secret with the slot publish profile.
![image](https://user-images.githubusercontent.com/48038149/100807138-a6458280-33e6-11eb-868b-21b5c9e92cb9.png)

**Comment by aksm-ms** [comment] 2020-12-03 11:26
@rue-kcarlton Are you still facing the issue?

**Comment by aksm-ms** [comment] 2020-12-04 05:22
@rue-kcarlton Can you check from your side and let me know if its working?

**Comment by rue-kcarlton** [comment] 2020-12-04 15:24
@aksm-ms Yes, I'm still having the issue... I changed my publish profile to be something like this
```
<publishData>
  <publishProfile profileName="my-api-staging - Web Deploy" publishMethod="MSDeploy" publishUrl="my-api-staging.scm.azurewebsites.net:443" msdeploySite="my-api__staging" userName="$my-api__staging" userPWD="***" destinationAppUrl="http://my-api-staging.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites">
    <databases/>
  </publishProfile>
  <publishProfile profileName="my-api-staging - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-blu-095.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="my-api__staging\$my-api__staging" userPWD="***" destinationAppUrl="http://my-api-staging.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites">
    <databases/>
  </publishProfile>
  <publishProfile profileName="my-api-staging - ReadOnly - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-blu-095dr.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="my-api__staging\$my-api__staging" userPWD="***" destinationAppUrl="http://my-api-staging.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites">
    <databases/>
  </publishProfile>
</publishData>
```
So the slot should match up at this point, but I'm still getting the same error:
```
Successfully parsed SCM credential from old publishProfile
Error: Execution Exception (state: ValidateParameter) (step: Invocation)
Error:   At ValidateParameter, slot-name : SCM credential does not match slot-name.
Error: Deployment Failed!
```

**Comment by aksm-ms** [comment] 2020-12-07 05:15
@Hazhzeng  can you please take a look at this?

**Comment by aksm-ms** [comment] 2020-12-08 09:04
@Hazhzeng Can you please update this?

**Comment by Hazhzeng** [comment] 2020-12-11 06:11
@aksm-ms, could you take a look at this?

**Comment by aksm-ms** [comment] 2021-01-13 08:02
@rue-kcarlton Are you still facing the issue? @Hazhzeng Can you please look into this? cc: @nadesu

**Comment by rue-kcarlton** [comment] 2021-01-13 15:41
@aksm-ms Yes, I'm still having this issue.  I've reverted to using v1.1.6 to keep it working.

**Comment by dastev-ms** [comment] 2021-01-22 23:03
I had a very similar issue today that may be related.  Essentially, my app name is `MyService` and the slot name is `deployment`, and I would get the "SCM credential does not match slot-name" error message.  However, using `myservice` as the app name fixed the issue entirely.  It looks like the default publish profile to-lowers everything, but the check that it's using the correct slot doesn't to-lower the input, so the check fails.  I would like to be able to use the correct casing for my yml, but the workaround gets the job done for me right now.

Then again, this could be an entirely different issue from @rue-kcarlton's

**Comment by Hazhzeng** [comment] 2021-01-28 23:54
Sorry for the late reply and thanks @dastev-ms for the investigation.

Hi @rue-kcarlton
This issue should be fixed now https://github.com/Azure/functions-action/blob/v1.3.1/src/handlers/parameterValidator.ts#L172-L173.

**Closed** 2021-02-02 22:41 UTC
Labels: bug, waiting-for-customer
